-- Blog CMS schema for kc.kevcspot.com
-- Stores blog posts generated by AI and created manually via CMS

-- pgcrypto is enabled by default in Supabase (provides gen_random_uuid)

-- Blog posts table
create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  description text not null,
  category text not null default 'General',
  tags text[] default '{}',
  author text not null default 'Kevin',
  is_ai_generated boolean not null default false,
  date date not null default current_date,
  read_time text not null default '5 min',
  accent text not null default 'cyan' check (accent in ('gold', 'cyan', 'purple')),
  content jsonb not null default '[]',
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Index for sorting by date
create index if not exists idx_blog_posts_date on public.blog_posts (date desc);
create index if not exists idx_blog_posts_category on public.blog_posts (category);
create index if not exists idx_blog_posts_slug on public.blog_posts (slug);

-- Auto-update updated_at on row change
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists blog_posts_updated_at on public.blog_posts;
create trigger blog_posts_updated_at
  before update on public.blog_posts
  for each row execute function public.handle_updated_at();

-- Enable Row Level Security
alter table public.blog_posts enable row level security;

-- Policy: anyone can read published posts
create policy "Public can read published posts"
  on public.blog_posts
  for select
  using (published = true);

-- Policy: only service_role can insert/update/delete
create policy "Service role can manage posts"
  on public.blog_posts
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- Project updates table
create table if not exists public.project_updates (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  project_slug text not null,
  project_name text not null,
  title text not null,
  description text not null,
  date date not null default current_date,
  accent text not null default 'gold' check (accent in ('gold', 'cyan', 'purple')),
  created_at timestamptz not null default now()
);

create index if not exists idx_project_updates_date on public.project_updates (date desc);

alter table public.project_updates enable row level security;

create policy "Public can read project updates"
  on public.project_updates
  for select
  using (true);

create policy "Service role can manage project updates"
  on public.project_updates
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
